name: weather
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  rxdart: ^0.27.5
  dartz: ^0.10.1
  uno: ^1.0.1+3

dev_dependencies:
  build_runner: 2.2.0 
  lints: ^2.0.0
  test: ^1.16.0
  mockito: 5.3.0
